export const unitMap: Record<string, string> = {
    gdp: 'USD',
    growthRate: '%',
    militarySpending: '% of GDP',
    armsExport: 'USD',
    innovationRank: 'Rank',
    productivity: 'USD/hour',
    higherEdRate: '%',
    avgYearsSchooling: 'years',
    globalCompetitiveness: 'Score(0~100)',
    economicComplexityRank: 'Rank',
    tradeVolume: 'USD',
    tradeDependency: '%',
    financialStability: 'Score(0~100)',
    forexReserve: 'USD',
    currencyShare: '% of IMF basket',
    trustInGov: '%',
    ruleOfLaw: 'Score(0~2.5)',
    unrestIndex: 'Index(0~100)',
    diplomacyScore: 'Score(0~100)',
  };